imports:
  - { resource: parameters.yml }
  - { resource: security.yml }
  - { resource: services.yml }
  - { resource: "@AppBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
  locale: ru
  sonata.admin.configuration.show.mosaic.button: false

framework:
  #esi: ~
  translator: { fallbacks: ['%locale%'] }
  secret: '%secret%'
  router:
    resource: '%kernel.project_dir%/app/config/routing.yml'
    strict_requirements: ~
  form: ~
  csrf_protection: ~
  validation: { enable_annotations: true }
  #serializer: { enable_annotations: true }
  default_locale: '%locale%'
  trusted_hosts: ~
  session:
    # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
    handler_id: session.handler.native_file
    save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
  fragments: ~
  http_method_override: true
  assets: ~
  templating:
    engines: ['twig']

  php_errors:
    log: true

# Twig Configuration
twig:
  debug: '%kernel.debug%'
  strict_variables: '%kernel.debug%'
  form_themes:
    - 'SonataCoreBundle:Form:datepicker.html.twig'
    - '@App/form/taxon_jstree_widget.html.twig'
    - '@App/form/text_block_collection.html.twig'
    - '@App/form/study_block_collection.html.twig'
    - '@App/form/article_content_widget.html.twig'
    - '@App/form/tiny_mce_lazy_widget.html.twig'

# Doctrine Configuration
doctrine:
  dbal:
    driver: pdo_mysql
    host: '%database_host%'
    port: '%database_port%'
    dbname: '%database_name%'
    user: '%database_user%'
    password: '%database_password%'
    charset: UTF8
    # if using pdo_sqlite as your database driver:
    #   1. add the path in parameters.yml
    #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
    #   2. Uncomment database_path in parameters.yml.dist
    #   3. Uncomment next line:
    #path: '%database_path%'

  orm:
    auto_generate_proxy_classes: '%kernel.debug%'
    naming_strategy: doctrine.orm.naming_strategy.underscore
    auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
  transport: '%mailer_transport%'
  host: '%mailer_host%'
  username: '%mailer_user%'
  password: '%mailer_password%'
  encryption: '%mailer_encryption%'
  port: '%mailer_port%'
  spool: { type: memory }

sensio_framework_extra:
  router:
    annotations: false

fos_user:
  db_driver: orm
  firewall_name: main
  user_class: AppBundle\Entity\User\User
  from_email:
    address: "%mailer_user%"
    sender_name: "%mailer_sender_name%"

sonata_admin:
  title: Раздел администрирования
  dashboard:
    groups:
      main:
        label: "Главная"
      resources:
        label: "Ресурсы"
      settings:
        label: "Настройки"
  options:
    html5_validate: false
    lock_protection: false
    use_select2: true

sonata_block:
  default_contexts: [cms]
  blocks:
    sonata.admin.block.admin_list:
      contexts: [admin]
    sonata.admin.block.search_result:
      contexts: [admin]

stof_doctrine_extensions:
  default_locale: ru_RU
  orm:
    default:
      timestampable: true
      tree: true
      sortable: true
      sluggable: true

stfalcon_tinymce:
  selector: ".tinymce"
  language: "ru"
  tinymce_buttons:
    video_select:
      title: 'Выбрать видео'
      icon: 'media'
  external_plugins:
    filemanager:
      url: "asset[fm/plugin.min.js]"
  theme:
    simple:
      theme: "modern"
      height: '520px'
      relative_urls: false
      external_filemanager_path: '/fm'
      plugins:
        - "advlist autolink lists link charmap print preview hr anchor pagebreak"
        - "searchreplace wordcount visualblocks visualchars code fullscreen"
        - "nonbreaking save table contextmenu directionality"
        - "emoticons template paste textcolor"
      toolbar1: "insertfile undo redo | cut copy paste insert pastetext | searchreplace | visualchars link unlink | blockquote hr openlink charmap anchor | emoticons | nonbreaking | spellchecker | code |  table | quote document"
      toolbar2: "styleselect  | formatselect | fontselect fontsizeselect | ltr rtl | bold italic underline strikethrough  removeformat subscript superscript | forecolor backcolor | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent"
      image_advtab: true
    article:
      theme: "modern"
      height: '520px'
      relative_urls: false
      external_filemanager_path: '/fm/'
      plugins:
        - "advlist autolink lists link image charmap print preview hr anchor pagebreak"
        - "searchreplace wordcount visualblocks visualchars code fullscreen"
        - "insertdatetime nonbreaking save table contextmenu directionality"
        - "emoticons template paste textcolor"
      toolbar1: "newdocument | insertfile undo redo | cut copy paste insert pastetext | print | searchreplace | visualchars"
      toolbar2: "styleselect  | formatselect | fontselect fontsizeselect | ltr rtl | bold italic underline strikethrough  removeformat subscript superscript | forecolor backcolor | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent"
      toolbar3: "image | link unlink | blockquote hr openlink charmap anchor | emoticons | nonbreaking | insertdatetime |pagebreak | spellchecker | code |  table | quote document | video_select"
      image_advtab: true